name: Kaplan.tv
favicon: null
layout_spectrum: 0.31517
typography_spectrum: 0.64724
title: Kaplan Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7097791-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#2b2e2b'
    - '#53686b'
    - '#84a4ae'
    - '#abcbd3'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5118976233061403
  rhythmicContrast: 0.75
purpose: []
