name: Kaplan.tv
favicon: null
layout_spectrum: 0.31517
typography_spectrum: 0.9519228253047913
title: Kaplan Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7097791-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 0.980869750957936
  saturation: 0.5118976233061403
  rhythmicContrast: 0.9772716178558767
purpose: []
