name: Kaplan.tv
favicon: null
layout_spectrum: 0.4916410769801587
typography_spectrum: 0.9519228253047913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5631224636454135
  lightness: 0.980869750957936
  saturation: 0.5118976233061403
  rhythmicContrast: 0.9772716178558767
purpose: []
