name: Kaplan.tv
favicon: null
layout_spectrum: 0.31517
typography_spectrum: 0.64724
title: Kaplan Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7097791-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#1e1e1e'
    - '#828282'
    - '#9c9da1'
    - '#4b5d10'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5118976233061403
  rhythmicContrast: 0.75
purpose: []
