name: www.Kaplan.tv
favicon: null
layout_spectrum: 0.31517
typography_spectrum: 0.64724
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Kaplan Electronic Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-7097791-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01030F'
    - '#033099'
    - '#3052A3'
    - '#FCFCFF'
    - '#6F86BE'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5118976233061403
  rhythmicContrast: 0.75
purpose: []
